### PR TITLE
Build with template-haskell-2.21 / ghc 9.8

### LINKED ISSUE #12: Build failure with template-haskell-2.21 (GHC 9.8)
```
src/Data/Lens/Light/Template.hs:102:22: error: [GHC-83865]
    • Couldn't match type ‘BndrVis’ with ‘()’
      Expected: [TyVarBndr']
        Actual: [TyVarBndr BndrVis]
    • In the first argument of ‘makeAccs’, namely ‘params’
      In the first argument of ‘(.)’, namely ‘makeAccs params’
      In the first argument of ‘($)’, namely ‘makeAccs params . nub’
    |
102 |     decs <- makeAccs params . nub $ concatMap namedFields cons
    |                      ^^^^^^
```
I make a hackage revision to place bound `template-haskell < 2.21`: https://hackage.haskell.org/package/data-lens-light-0.1.2.3/revisions/

### PR DESCRIPTION
**Pull request by andreasabel**
Changes to build with template-haskell-2.21 / GHC 9.8
Fixes #12.
- #12 

Please release on hackage!

Separate commits:
- Delete trailing whitespace
- Avoid x-partial warning with GHC 9.8: don't use head/tail
- Fix build with template-haskell-2.21
- Version 0.1.2.4
- Update CI

### CODE REVIEW

**Comment by andreasabel** [comment]
ATTN: @sorki

**Comment by andreasabel** [comment]
CI failed because it is outdated (wants to run on ubuntu-18.04 which is no longer supported by github actions).
I added a commit that updates CI so it can run again.

**Comment by sorki** [comment]
> @sorki could you please start the workflow again? Thx!

Oh, thank you! I've checked earlier but it was stuck waiting for workers. Anyway I'll merge and release this tomorrow as it looks good. I was a bit surprised that I didn't see template-haskell 2.21 on Hackage yesterday but CI seems happy.

**Comment by andreasabel** [comment]
> I was a bit surprised that I didn't see template-haskell 2.21 on Hackage yesterday but CI seems happy.

`template-haskell-2.21` is shipped with GHC 9.8.1-alpha1 and has not been published to Hackage yet.
Note that CI does not test on GHC 9.8---I tested this locally.  CI only ensures that on the properly released GHCs everything still works.

**Comment by sorki** [comment]
I see, thanks for the explanation and patches! Tagged and uploaded to Hackage.
